import FWCore.ParameterSet.Config as cms



zzCompositeTriggerBranches = cms.PSet(
    trigNames = cms.vstring('doubleMu', 'doubleMuDZ', 'doubleE',
                            'singleESingleMu', 'singleMuSingleE',
                            'tripleE', 'doubleESingleMu', 'doubleMuSingleE',
                            'tripleMu', 'singleE', 'singleIsoMu',
                            'singleIsoMu20', 'singleMu',),
    doubleMuPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v[0-9]+',
                                'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v[0-9]+'),
    doubleMuDZPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v[0-9]+',
                                  'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v[0-9]+'),
    doubleEPaths = cms.vstring('HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+',
                               'HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+',
                               'HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_v[0-9]+'),
    singleESingleMuPaths = cms.vstring('HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_v[0-9]+',
                                       'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v[0-9]+'),
    singleMuSingleEPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v[0-9]+',
                                       'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v[0-9]+'),
    tripleEPaths = cms.vstring('HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v[0-9]+'),
    doubleESingleMuPaths = cms.vstring('HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v[0-9]+'),
    doubleMuSingleEPaths = cms.vstring('HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v[0-9]+'),
    tripleMuPaths = cms.vstring('HLT_TripleMu_12_10_5_v[0-9]+'),
    singleEPaths = cms.vstring('HLT_Ele25_eta2p1_WPTight_Gsf_v[0-9]+',
                               'HLT_Ele27_WPTight_Gsf_v[0-9]+',
                               'HLT_Ele27_eta2p1_WPLoose_Gsf_v[0-9]+',),
    singleIsoMu20Paths = cms.vstring('HLT_IsoMu20_v[0-9]+',
                                     'HLT_IsoTkMu20_v[0-9]+',),
    singleIsoMuPaths = cms.vstring('HLT_IsoMu22_v[0-9]+',
                                   'HLT_IsoTkMu22_v[0-9]+',),
    singleMuPaths = cms.vstring('HLT_Mu50_v[0-9]+',
                                'HLT_Mu45_eta2p1_v[0-9]+',),

    trigResultsSrc = cms.InputTag("TriggerResults", "", "HLT"),
    trigPrescaleSrc = cms.InputTag("patTrigger"),

    checkPrescale = cms.bool(False),
    )
verboseTriggerBranches = cms.PSet(
    trigNames = cms.vstring(
        "HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL",
        "HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL",
        "HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ",
        "HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ",
        "HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ",
        "HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ",
        "HLT_DoubleEle33_CaloIdL_GsfTrkIdVL",
        "HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL",
        "HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL",
        "HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL",
        "HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL",
        'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ',
        'HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ',
        "HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL",
        "HLT_Mu8_DiEle12_CaloIdL_TrackIdL",
        "HLT_DiMu9_Ele9_CaloIdL_TrackIdL",
        "HLT_TripleMu_12_10_5",
        "HLT_Ele25_eta2p1_WPTight_Gsf",
        "HLT_Ele27_WPTight_Gsf",
        "HLT_Ele27_eta2p1_WPLoose_Gsf",
        "HLT_IsoMu20",
        "HLT_IsoTkMu20",
        "HLT_IsoMu22",
        "HLT_IsoTkMu22",
        "HLT_Mu50",
        "HLT_Mu45_eta2p1",
    ),
    HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVLPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v[0-9]+'),
    HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVLPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v[0-9]+'),
    HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v[0-9]+'),
    HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v[0-9]+'),
    HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZPaths = cms.vstring('HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+'),
    HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZPaths = cms.vstring('HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+'),
    HLT_DoubleEle33_CaloIdL_GsfTrkIdVLPaths = cms.vstring('HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_v[0-9]+'),
    HLT_DoubleEle33_CaloIdL_GsfTrkIdL_MWPaths = cms.vstring('HLT_DoubleEle33_CaloIdL_MW_v[0-9]+'),
    HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVLPaths = cms.vstring('HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_v[0-9]+'),
    HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVLPaths = cms.vstring('HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v[0-9]+'),
    HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZPaths =cms.vstring('HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+'),
    HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVLPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v[0-9]+'),
    HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVLPaths = cms.vstring('HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v[0-9]+'),
    HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZPaths = cms.vstring('HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+'),
    HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZPaths = cms.vstring('HLT_Mu23_TrkIsoVVL_Ele8_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+'),
    HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdLPaths = cms.vstring('HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v[0-9]+'),
    HLT_Mu8_DiEle12_CaloIdL_TrackIdLPaths = cms.vstring('HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v[0-9]+'),
    HLT_DiMu9_Ele9_CaloIdL_TrackIdLPaths = cms.vstring('HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v[0-9]+'),
    HLT_TripleMu_12_10_5Paths = cms.vstring('HLT_TripleMu_12_10_5_v[0-9]+'),
    HLT_Ele25_eta2p1_WPTight_GsfPaths = cms.vstring('HLT_Ele25_eta2p1_WPTight_Gsf_v[0-9]+'),
    HLT_Ele27_WPTight_GsfPaths = cms.vstring('HLT_Ele27_WPTight_Gsf_v[0-9]+'),
    HLT_Ele27_eta2p1_WPLoose_GsfPaths = cms.vstring('HLT_Ele27_eta2p1_WPLoose_Gsf_v[0-9]+'),
    HLT_IsoMu20Paths = cms.vstring('HLT_IsoMu20_v[0-9]+'),
    HLT_IsoTkMu20Paths = cms.vstring('HLT_IsoTkMu20_v[0-9]+'),
    HLT_IsoMu22Paths = cms.vstring('HLT_IsoMu22_v[0-9]+'),
    HLT_IsoMu24444Paths = cms.vstring('HLT_IsoMu24_v[0-9]+'),
    HLT_IsoMuTkMu24Paths = cms.vstring('HLT_IsoTkMu24_v[0-9]+'),
    HLT_IsoTkMu22Paths = cms.vstring('HLT_IsoTkMu22_v[0-9]+'),
    HLT_Mu50Paths = cms.vstring('HLT_Mu50_v[0-9]+'),
    HLT_Mu45_eta2p1Paths = cms.vstring('HLT_Mu45_eta2p1_v[0-9]+'),
    trigResultsSrc = cms.InputTag("TriggerResults", "", "HLT"),
    trigPrescaleSrc = cms.InputTag("patTrigger"),

    checkPrescale = cms.bool(False),
    ignoreMissing = cms.untracked.bool(True),
    )

triggerBranches_2016G = cms.PSet(
    trigNames = cms.vstring('doubleMu', 'doubleMuDZ', 'doubleE',
                            'singleESingleMu', 'singleMuSingleE',
                            'tripleE', 'doubleESingleMu', 'doubleMuSingleE',
                            'tripleMu', 'singleE', 'singleIsoMu',
                            'singleIsoMu20', 'singleMu',),
    doubleMuPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v[0-9]+',
                                'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v[0-9]+'),
    doubleMuDZPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v[0-9]+',
                                  'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v[0-9]+'),
    doubleEPaths = cms.vstring('HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+',
                               'HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+',
                               'HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_v[0-9]+'),
    singleESingleMuPaths = cms.vstring('HLT_Mu8_TrkIsoVVL_Ele17_CaloIdL_TrackIdL_IsoVL_v[0-9]+',
                                       'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_v[0-9]+',
                                       'HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+'),
    singleMuSingleEPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v[0-9]+',
                                       'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_v[0-9]+',
                                       'HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+'),
    tripleEPaths = cms.vstring('HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v[0-9]+'),
    doubleESingleMuPaths = cms.vstring('HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v[0-9]+'),
    doubleMuSingleEPaths = cms.vstring('HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v[0-9]+'),
    tripleMuPaths = cms.vstring('HLT_TripleMu_12_10_5_v[0-9]+'),
    singleEPaths = cms.vstring('HLT_Ele25_eta2p1_WPTight_Gsf_v[0-9]+',
                               'HLT_Ele27_WPTight_Gsf_v[0-9]+',
                               'HLT_Ele27_eta2p1_WPLoose_Gsf_v[0-9]+',),
    singleIsoMu20Paths = cms.vstring('HLT_IsoMu20_v[0-9]+',
                                     'HLT_IsoTkMu20_v[0-9]+',),
    singleIsoMuPaths = cms.vstring('HLT_IsoMu22_v[0-9]+',
                                   'HLT_IsoTkMu22_v[0-9]+',
                                   'HLT_IsoMu24_v[0-9]+',
                                   'HLT_IsoTkMu24_v[0-9]+',),
    singleMuPaths = cms.vstring('HLT_Mu50_v[0-9]+',
                                'HLT_Mu45_eta2p1_v[0-9]+',),

    trigResultsSrc = cms.InputTag("TriggerResults", "", "HLT"),
    trigPrescaleSrc = cms.InputTag("patTrigger"),

    checkPrescale = cms.bool(False),
    )

triggerBranches_2016H = cms.PSet(
    trigNames = cms.vstring('doubleMu', 'doubleMuDZ', 'doubleE',
                            'singleESingleMu', 'singleMuSingleE',
                            'tripleE', 'doubleESingleMu', 'doubleMuSingleE',
                            'tripleMu', 'singleE', 'singleIsoMu',
                            'singleIsoMu20', 'singleMu',),
    doubleMuPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_v[0-9]+',
                                'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_v[0-9]+'),
    doubleMuDZPaths = cms.vstring('HLT_Mu17_TrkIsoVVL_Mu8_TrkIsoVVL_DZ_v[0-9]+',
                                  'HLT_Mu17_TrkIsoVVL_TkMu8_TrkIsoVVL_DZ_v[0-9]+'),
    doubleEPaths = cms.vstring('HLT_Ele23_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+',
                               'HLT_Ele17_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+',
                               'HLT_DoubleEle33_CaloIdL_GsfTrkIdVL_MW_v[0-9]+',
                               'HLT_DoubleEle33_CaloIdL_MW_v[0-9]+'),
    singleESingleMuPaths = cms.vstring('HLT_Mu8_TrkIsoVVL_Ele23_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+'),
    singleMuSingleEPaths = cms.vstring('HLT_Mu23_TrkIsoVVL_Ele12_CaloIdL_TrackIdL_IsoVL_DZ_v[0-9]+'),
    tripleEPaths = cms.vstring('HLT_Ele16_Ele12_Ele8_CaloIdL_TrackIdL_v[0-9]+'),
    doubleESingleMuPaths = cms.vstring('HLT_Mu8_DiEle12_CaloIdL_TrackIdL_v[0-9]+'),
    doubleMuSingleEPaths = cms.vstring('HLT_DiMu9_Ele9_CaloIdL_TrackIdL_v[0-9]+'),
    tripleMuPaths = cms.vstring('HLT_TripleMu_12_10_5_v[0-9]+'),
    singleEPaths = cms.vstring('HLT_Ele25_eta2p1_WPTight_Gsf_v[0-9]+',
                               'HLT_Ele27_WPTight_Gsf_v[0-9]+',
                               'HLT_Ele27_eta2p1_WPLoose_Gsf_v[0-9]+',),
    singleIsoMu20Paths = cms.vstring('HLT_IsoMu20_v[0-9]+',
                                     'HLT_IsoTkMu20_v[0-9]+',),
    singleIsoMuPaths = cms.vstring('HLT_IsoMu22_v[0-9]+',
                                   'HLT_IsoTkMu22_v[0-9]+',
                                   'HLT_IsoMu24_v[0-9]+',
                                   'HLT_IsoTkMu24_v[0-9]+',),
    singleMuPaths = cms.vstring('HLT_Mu50_v[0-9]+',
                                'HLT_Mu45_eta2p1_v[0-9]+',),

    trigResultsSrc = cms.InputTag("TriggerResults", "", "HLT"),
    trigPrescaleSrc = cms.InputTag("patTrigger"),

    checkPrescale = cms.bool(False),
    )

# Bad Muon filter for ReMiniAOD following: https://twiki.cern.ch/twiki/bin/view/CMSPublic/ReMiniAOD03Feb2017Notes
# MET filters for Moriond 2017 following: https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2
metAndBadMuonFilters = cms.PSet(
    trigNames = cms.vstring(
        'Flag_HBHENoiseFilter', 
        'Flag_HBHENoiseIsoFilter',
        'Flag_EcalDeadCellTriggerPrimitiveFilter',
        'Flag_goodVertices',
        'Flag_eeBadScFilter',
        'Flag_globalTightHalo2016Filter',
        'Flag_badMuons', 
        'Flag_duplicateMuons',
    ),
    Flag_HBHENoiseFilterPaths = cms.vstring('Flag_HBHENoiseFilter'),
    Flag_HBHENoiseIsoFilterPaths = cms.vstring('Flag_HBHENoiseIsoFilter'),
    Flag_EcalDeadCellTriggerPrimitiveFilterPaths = cms.vstring('Flag_EcalDeadCellTriggerPrimitiveFilter'),
    Flag_goodVerticesPaths = cms.vstring('Flag_goodVertices'),
    Flag_eeBadScFilterPaths = cms.vstring('Flag_eeBadScFilter'),
    Flag_globalTightHalo2016FilterPaths = cms.vstring('Flag_globalTightHalo2016Filter'),
    Flag_BadChargedCandidateFilterPaths = cms.vstring('Flag_BadChargedCandidateFilter'),
    Flag_BadPFMuonFilterPaths = cms.vstring('Flag_BadPFMuonFilter'),
    
    Flag_badMuonsPaths = cms.vstring('Flag_badMuons'),
    Flag_duplicateMuonsPaths = cms.vstring('Flag_duplicateMuons'),
    trigResultsSrc = cms.InputTag("TriggerResults", "", "PAT"),
    trigPrescaleSrc = cms.InputTag("patTrigger"),
    checkPrescale = cms.bool(False),
    )

# MET filters for Moriond 2017 following: https://twiki.cern.ch/twiki/bin/viewauth/CMS/MissingETOptionalFiltersRun2
metFilters = cms.PSet(
    trigNames = cms.vstring(
        'Flag_HBHENoiseFilter', 
        'Flag_HBHENoiseIsoFilter',
        'Flag_EcalDeadCellTriggerPrimitiveFilter',
        'Flag_goodVertices',
        'Flag_eeBadScFilter',
        'Flag_globalTightHalo2016Filter',
    ),
    Flag_HBHENoiseFilterPaths = cms.vstring('Flag_HBHENoiseFilter'),
    Flag_HBHENoiseIsoFilterPaths = cms.vstring('Flag_HBHENoiseIsoFilter'),
    Flag_EcalDeadCellTriggerPrimitiveFilterPaths = cms.vstring('Flag_EcalDeadCellTriggerPrimitiveFilter'),
    Flag_goodVerticesPaths = cms.vstring('Flag_goodVertices'),
    Flag_eeBadScFilterPaths = cms.vstring('Flag_eeBadScFilter'),
    Flag_globalTightHalo2016FilterPaths = cms.vstring('Flag_globalTightHalo2016Filter'),
    
    trigResultsSrc = cms.InputTag("TriggerResults", "", "PAT"),
    trigPrescaleSrc = cms.InputTag("patTrigger"),
    checkPrescale = cms.bool(False),
    )
